- name: Create AWS Cognito User Pool with additional configurations, required attributes, and optional MFA
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a new Cognito User Pool with sign-up settings, required attributes, and optional MFA
      boto3:
        service: cognito-idp
        operation: create_user_pool
        parameters: 
          PoolName: "GameOnNowUserPool"
          UsernameAttributes:
            - email
          Schema:
            - Name: email
              AttributeDataType: String
              Required: true
              Mutable: false
            - Name: given_name
              AttributeDataType: String
              Required: true
              Mutable: true
            - Name: family_name
              AttributeDataType: String
              Required: true
              Mutable: true
            - Name: birthdate
              AttributeDataType: Date
              Required: true
              Mutable: true
            - Name: phone_number
              AttributeDataType: String
              Required: true
              Mutable: true
            - Name: preferred_username
              AttributeDataType: String
              Required: true
              Mutable: true
            - Name: gender
              AttributeDataType: String
              Required: true
              Mutable: true
          Policies:
            PasswordPolicy:
              MinimumLength: 8
              RequireLowercase: true
              RequireNumbers: true
              RequireSymbols: true
              RequireUppercase: true
          MfaConfiguration: OPTIONAL
          SmsMfaConfiguration:
            SmsAuthenticationMessage: "Your authentication code is {####}"