- name: Create AWS Cognito User Pool with additional configurations, required attributes, and optional MFA
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install boto3 using pip
      pip:
        name: boto3
        state: present
    - name: Debug - List installed Python packages
      command: "pip list"
    - name: Create a new Cognito User Pool with sign-up settings, required attributes, and optional MFA
      boto3:
        service: cognito-idp
        operation: create_user_pool
        parameters: 
          PoolName: "GameOnNowUserPool"
          UsernameAttributes:
            - email
          Schema:
            - Name: email
              AttributeDataType: String
              Required: true
              Mutable: false
            - Name: given_name
              AttributeDataType: String
              Required: true
              Mutable: true
            - Name: family_name
              AttributeDataType: String
              Required: true
              Mutable: true
            - Name: birthdate
              AttributeDataType: Date
              Required: true
              Mutable: true
            - Name: phone_number
              AttributeDataType: String
              Required: true
              Mutable: true
            - Name: preferred_username
              AttributeDataType: String
              Required: true
              Mutable: true
            - Name: gender
              AttributeDataType: String
              Required: true
              Mutable: true
          Policies:
            PasswordPolicy:
              MinimumLength: 8
              RequireLowercase: true
              RequireNumbers: true
              RequireSymbols: true
              RequireUppercase: true
          MfaConfiguration: OPTIONAL
          SmsMfaConfiguration:
            SmsAuthenticationMessage: "Your authentication code is {####}"
            SmsVerificationMessage: "Your verification code is {####}"
          EmailVerificationMessage: "Please click the link below to verify your email address. {####}"
          EmailVerificationSubject: "Your verification link"
      register: cognito_user_pool

    - name: Output new Cognito User Pool ID
      debug:
        msg: "New user pool ID is {{ cognito_user_pool.UserPool.Id }}"
